image: bitriseio/docker-android:latest

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

cache:
  key: $CI_PROJECT_NAME
  paths:
    - .gradle/wrapper
    - .gradle/caches

merge_request:
  stage: test
  artifacts:
    when: always
    paths:
      - "*/build/reports"
  tags:
    - docker
    - x86
  only:
    - merge_requests
  script:
    - ./gradlew runAll

deploy_release:
  stage: deploy
  artifacts:
    when: always
    paths:
      - "*/build/reports"
      - "*/build/outputs/aar"
  tags:
    - docker
    - x86
  only:
    - tags
  script:
    - ./gradlew runAll uploadArchives
